services:
  mcp-gameboy:
    build: .
    image: mcp-gameboy:sse
    container_name: mcp-gameboy
    ports:
      - "3001:3001"
    volumes:
      - /home/docker/mcp-gameboy_config/rom:./roms
    restart: unless-stopped
    # opzionale: override config
    #environment:
    #  SERVER_PORT: "3001"
    #  ROM_PATH: "/app/roms/PokemonRed.gb"