services:
  mcp-gameboy:
    build: .
    image: mcp-gameboy:sse
    container_name: mcp-gameboy
    ports:
      - "3001:3001"
    volumes:
      - /home/docker/mcp-gameboy_config/rom:/app/roms
    restart: unless-stopped